### ISSUE TITLE
Diagrame UML de use-case

### ISSUE THREAD

**Issue by puiusebastian** [puiusebastian/TIP#8]

**Comment by ilie05** [comment]
![use_case tank](https://user-images.githubusercontent.com/33878321/37776468-04ea600a-2dee-11e8-99b9-a4bbe5be4ca6.jpg)

**Comment by ilie05** [comment]
Diagrama use-case este un tip de diagramă din care reiese modul de interactionare cu sistemul si prezinta relatiile dintre actori si posibilele cazuri de utilizare a sistemului in care fiecare actor poate fi implicat. Actorii in cazul dat sunt user-ul standard, player-ul si server-ul de servicii web.

**Comment by ilie05** [comment]
![use_case_tank](https://user-images.githubusercontent.com/33878321/37777830-27cbeb0e-2df1-11e8-98fe-1c677b2d0114.jpg)
